### ISSUE TITLE
Method parameter with enum type seems buggy

### ISSUE THREAD

**Issue by igrir** [ddionisio/MateAnimator#16]
Yesterday I made a method with parameter of enum in animation for Event track. At first the method show up, but then after I close and open the cutscene editor again the errors pop up on console.

**Comment by ddionisio** [comment]
Hi,

I've added some extra checks for enums.  It may have been possible that the type signature has changed after a key has been added.

If it still occurs, can you post the full exception log here?

**Comment by igrir** [comment]
It's fixed and amazingly works. Thanks! :+1:
