### ISSUE TITLE
Error on EventTrack when method is null

### ISSUE THREAD

**Issue by igrir** [ddionisio/MateAnimator#18]
Hi @ddionisio! It's been a long time :octocat: 
Just today I realized if I put nothing on GameObject parameter in Event track it would return error. Here's the error I've got

`NullReferenceException: Object reference not set to an instance of an object
MateAnimator.AMActionMethodCall.Apply (Single t, Boolean backwards) (at Assets/Plugins/MateAnimator/Scripts/Classes/AMActionTween.cs:471)
MateAnimator.AMActionTween.DoUpdate (Single p_totElapsed) (at Assets/Plugins/MateAnimator/Scripts/Classes/AMActionTween.cs:92)
Holoville.HOTween.Plugins.Core.ABSTweenPlugin.Update (Single p_totElapsed) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__HOTween.Assembly/HOTweenV1/Plugins/Core/ABSTweenPlugin.cs:469)
Holoville.HOTween.Tweener.Update (Single p_shortElapsed, Boolean p_forceUpdate, Boolean p_isStartupIteration, Boolean p_ignoreCallbacks, Boolean p_ignoreDelay) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__HOTween.Assembly/HOTweenV1/Tweener.cs:844)
Holoville.HOTween.Tweener.GoTo (Single p_time, Boolean p_play, Boolean p_forceUpdate, Boolean p_ignoreCallbacks) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__HOTween.Assembly/HOTweenV1/Tweener.cs:951)
Holoville.HOTween.Core.ABSTweenComponent.GoTo (Single p_time, Boolean p_forceUpdate) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__HOTween.Assembly/HOTweenV1/Core/ABSTweenComponent.cs:659)
Holoville.HOTween.Sequence.Update (Single p_shortElapsed, Boolean p_forceUpdate, Boolean p_isStartupIteration, Boolean p_ignoreCallbacks) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__HOTween.Assembly/HOTweenV1/Sequence.cs:749)
Holoville.HOTween.Core.ABSTweenComponent.Update (Single p_elapsed) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__HOTween.Assembly/HOTweenV1/Core/ABSTweenComponent.cs:954)
Holoville.HOTween.HOTween.DoUpdate (UpdateType p_updateType, Single p_elapsed) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__HOTween.Assembly/HOTweenV1/HOTween.cs:2252)
Holoville.HOTween.HOTween.Update () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__HOTween.Assembly/HOTweenV1/HOTween.cs:734)
`

**Comment by ddionisio** [comment]
I'll take a look at it when I get around.

**Comment by ddionisio** [comment]
I wasn't able to repro with that exact error, but there was another exception if I have a GameObject as null for parameter.  I've made it so that it references the actual object of UnityEngine.Object to alleviate that.  I've put a null check for method and target object as well, if for some reason its reference is disappearing.

Let me know if that works for you.  If it doesn't error out, but you expect an object to be valid, double check if that object during runtime is getting deleted somehow.

**Comment by tomaszzackiewicz** [comment]
Hello,

I have installed DOTween and MateAnimator, however I get many errors. The first one is:

Assets/MateAnimator-master/Scripts/Classes/AMMaterialKey.cs(134,48): error CS0246: The type or namespace name `Vector4Plugin' could not be found. Are you missing an assembly reference?

**Comment by ddionisio** [comment]
Looks like it has something to do with the compatibility mode (hyper compatible version).  Basically instead of Vector3Plugin, it's Vector3WrapperPlugin.

Let me go through and add a compile flag around those places.

So once I'm done, there should be a new define symbol you'll need to add in the player settings DOTWEEN_HYPER_COMPATIBLE

I'll reply here once I check it in.

**Comment by tomaszzackiewicz** [comment]
Ok, thank you.

**Comment by ddionisio** [comment]
If you get the latest, you should be able to fix the issue now.

Basically add **DOTWEEN_HYPER_COMPATIBLE** to Scripting Define Symbols in Edit->Project Settings->Player

**Comment by tomaszzackiewicz** [comment]
Sorry for late answer, but it doesn't work. It changed nothing. Still the errors.

**Comment by ddionisio** [comment]
I am assuming you are using DOTween's hyper compatible version.

You have to add the define symbol **DOTWEEN_HYPER_COMPATIBLE** in the projects settings.

1) In Unity editor, go to the menu Edit->Project Settings->Player
2) In the inspector, go to Other Settings
3) Look for Scripting Define Symbols
4) In Scripting Define Symbols, type in: **DOTWEEN_HYPER_COMPATIBLE**
5) Once that setting is applied, Unity should recompile and errors should go away.

**Comment by tomaszzackiewicz** [comment]
Yes, I use DOTween's hyper compatible version. I have done exactly what you said. The same.

**Comment by ddionisio** [comment]
Check the settings to the platform target you are currently using, ie. Standalone, Android, etc.

Make sure **DOTWEEN_HYPER_COMPATIBLE** is in the one you have as the active platform target.  So if you go to File->Build Settings... Look in the Platform window and the active target is the one with the Unity icon.  Check the Player Settings for that.

**Comment by tomaszzackiewicz** [comment]
Sorry, but all is OK. I use the Standalone in the Build Settings and clicking the Player Settings I will see DOTWEEN_HYPER_COMPATIBLE under Scripting Define Symbols.

Please install the recent Unity and add your code. I would like to know whether you get errors or not.

**Comment by ddionisio** [comment]
I tried it on 5.5.0f3

Prior to the fix, I was getting the exacts error you were getting.  So the latest from the repo should have taken care of it.

Can you create an empty project with the plugins MateAnimator and DOTween in it (the ones you were using in the project with the issue)?  Then attach it in your message.

**Comment by tomaszzackiewicz** [comment]
My fresh project with the errors:

[TestTimeline.zip](https://github.com/ddionisio/MateAnimator/files/685797/TestTimeline.zip)

**Comment by ddionisio** [comment]
Are you doing anything custom with the code project settings? (Monodevelop or Visual .NET)

Sometimes the code project gets desynced with the project, it should be safe to delete those files (solution files).  Just make sure to back up.

Looks like it has something to do with the define symbol not getting added somehow.

If all else fails, add this line at the top of AMPluginFactory.cs:

`#define DOTWEEN_HYPER_COMPATIBLE`

**Comment by tomaszzackiewicz** [comment]
> Are you doing anything custom with the code project settings? (Monodevelop or Visual .NET).

Not yet. I wish in the future, but the project is clean with default settings.

**Comment by ddionisio** [comment]
Ah, I see what's going on now.

You need to get the latest of MateAnimator, you'll know it's the latest if you get the AMPluginFactory.cs

**Comment by tomaszzackiewicz** [comment]
> Ah, I see what's going on now.
> 
> You need to get the latest of MateAnimator, you'll know it's the latest if you get the AMPluginFactory.cs

I thought this version is the latest. Where I can get the latest version?

**Comment by ddionisio** [comment]
Should be in the master branch.  If you want to just download it, it should be available in the repo's page via Clone or download

**Comment by tomaszzackiewicz** [comment]
I downloaded the zip. i have no idea why it is not recent. I will try again tomorrow.

**Comment by tomaszzackiewicz** [comment]
I have downloaded the zip master again and .. IT WORKS! Thank you. I can add that earlier I downloaded the zip master too and it didn't work.

**Comment by ddionisio** [comment]
No problem!  Glad that worked out.
